"""
Django settings for GiftcardSite project.

Generated by 'django-admin startproject' using Django 3.0.8.
[rtb325] now using django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import base64
from dotenv import load_dotenv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = os.path.join(BASE_DIR, ".env")
load_dotenv('.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Key Management [rtb325]
testing_key = 'h6sw5pbCtepUOkybKKs2wMauu92unsJ2ErHKYQtFZ58='
real_key = os.environ.get('KEY1')

if real_key is None:
    SECRET_KEY = testing_key
else:
    SECRET_KEY = real_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom
    'LegacySite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
     #csrf middleware added for blanket protection [rtb325]
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GiftcardSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GiftcardSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static Images:

IMAGE_ROOT = os.path.join(BASE_DIR, 'images')

# JS Root.

JS_ROOT = os.path.join(BASE_DIR, "templates/js")

# CSS Root

CSS_ROOT = os.path.join(BASE_DIR, "templates/css")

# Font Root
FONT_ROOT = os.path.join(BASE_DIR, "templates/fonts")

# Random Seed for testing
RANDOM_SEED = base64.b64decode("2RUHYAyJWdDdXOicZfnTRw==")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Auth Backends
AUTHENTICATION_BACKENDS = ['LegacySite.models.OurBackend']

# Django 3.2 compat
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# ShoddyCorp note: hack to get around stupid browser restrictions.
# Fixes issue with Chrome not allowing partner sites to access the site.
SESSION_COOKIE_SAMESITE = 'Lax'
# Don't know if this is necessary but all this stupid security stuff just
# makes my job harder
# [rtb325]: JS fix
SESSION_COOKIE_HTTPONLY = True
